name: Trigger Dependabot on Push

on: [push]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Dependabot
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/dependency-graph/snapshots
