name: Test SHA Updates

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      trigger_dependabot:
        description: 'Trigger Dependabot update check'
        required: false
        default: 'false'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # सभी push इवेंट्स पर Dependabot चेक ट्रिगर करें
      - name: Trigger Dependabot on push
        if: github.event_name == 'push'
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/dependency-graph/snapshots
      
      # मैन्युअल ट्रिगर के लिए Dependabot चेक
      - name: Trigger Dependabot if requested
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.trigger_dependabot == 'true' }}
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/dependency-graph/snapshots
      
      - uses: tj-actions/changed-files@2f7c5bfce28377bc069a65ba478de0a74aa0ca32 # v46.0.1
