name: Test SHA Updates

on:
  push:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # This is what Dependabot should update
      - uses: tj-actions/changed-files@e5b971c8c92a4e6e3c91e3d058951c6c8b9269a1 # v35.0.2
      # ^ Dependabot should update to v46.0.4 automatically
